version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: elmenus-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - elmenus-network
    restart: unless-stopped

networks:
  elmenus-network:
    driver: bridge

volumes:
  postgres-data:
